# Generated by Django 4.2.7 on 2023-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coba',
            name='id',
        ),
        migrations.AddField(
            model_name='coba',
            name='myid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
