# Generated by Django 4.2.7 on 2023-12-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0002_remove_coba_id_coba_myid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('Kode', models.CharField(default='', max_length=3, primary_key=True, serialize=False, verbose_name='Kode Jabatan')),
                ('Nama_Jabatan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('NIP', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Nomor Induk Pegawai')),
                ('Nama', models.CharField(max_length=50, verbose_name='Nama Pegawai')),
                ('Kelamin', models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], max_length=1)),
                ('Jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat.jabatan', verbose_name='Jabatan')),
            ],
        ),
    ]
