# Generated by Django 4.2.7 on 2023-12-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0005_dasarsurattugas_konfigurasi_st_dasar_st_peserta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realuser',
            name='isList',
        ),
    ]
