# Generated by Django 4.2.7 on 2023-12-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0006_remove_realuser_islist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surattugas',
            name='Kepala_Bapeda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
