# Generated by Django 4.2.7 on 2023-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0007_alter_surattugas_kepala_bapeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surattugas',
            name='Tanggal_Surat',
            field=models.DateTimeField(),
        ),
    ]
