# Generated by Django 4.2.7 on 2023-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0010_alter_surattugas_tanggal_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='surattugas',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
