# Generated by Django 4.2.7 on 2023-12-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0012_alter_st_dasar_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surattugas',
            name='ID_NomorSurat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
