# Generated by Django 4.2.7 on 2023-12-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0016_alter_laporaneval_nomor_surat_eval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanEval_bmd_bergerak',
            fields=[
                ('Nomor_Surat_Eval', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='surat.laporaneval')),
                ('Detail', models.TextField(default='', verbose_name='Detail Asset tak Bergerak')),
            ],
        ),
    ]
