# Generated by Django 4.2.7 on 2023-12-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0017_laporaneval_bmd_bergerak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporaneval_bmd_bergerak',
            name='Detail',
            field=models.TextField(default='', primary_key=True, serialize=False, verbose_name='Detail Asset tak Bergerak'),
        ),
        migrations.AlterField(
            model_name='laporaneval_bmd_bergerak',
            name='Nomor_Surat_Eval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat.laporaneval'),
        ),
    ]
