# Generated by Django 4.2.7 on 2023-12-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0018_alter_laporaneval_bmd_bergerak_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanEval_bmd_bergerak_kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kendaraan', models.CharField(default='', max_length=50)),
                ('Detail', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat.laporaneval_bmd_bergerak')),
            ],
        ),
    ]
