# Generated by Django 4.2.7 on 2023-12-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0019_laporaneval_bmd_bergerak_kendaraan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanEval_pkb_perbandingan',
            fields=[
                ('Keterangan', models.TextField(default='', primary_key=True, serialize=False)),
                ('Total_tahun1', models.BigIntegerField(default=0)),
                ('Total_tahun2', models.BigIntegerField(default=0)),
                ('Total_selisih', models.BigIntegerField(default=0)),
                ('Alasan', models.CharField(max_length=200)),
                ('Detail', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat.laporaneval')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanEval_pkb_perbandingan_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun1', models.BigIntegerField(default=0)),
                ('tahun2', models.BigIntegerField(default=0)),
                ('bulan', models.CharField(choices=[('JA', 'JANUARI'), ('FE', 'FEBRUARI'), ('MA', 'MARET'), ('AP', 'APRIL'), ('ME', 'MEI'), ('JU', 'JUNI'), ('JL', 'JULI'), ('AG', 'AGUSTUS'), ('SE', 'SEPTEMBER'), ('OK', 'OKTOBER'), ('NO', 'NOVEMBER'), ('DE', 'DESEMBER')], default='JA', max_length=2)),
                ('Keterangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat.laporaneval_pkb_perbandingan')),
            ],
        ),
    ]
