# Generated by Django 4.2.7 on 2023-12-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0020_laporaneval_pkb_perbandingan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporaneval',
            name='Periode_Akhir',
            field=models.CharField(max_length=20, verbose_name='Periode Akhir'),
        ),
        migrations.AlterField(
            model_name='laporaneval',
            name='Periode_Awal',
            field=models.CharField(max_length=20, verbose_name='Periode Awal'),
        ),
        migrations.AlterField(
            model_name='laporaneval',
            name='Periode_Pegawai',
            field=models.CharField(max_length=20, verbose_name='Periode Pengecekan Pegawai'),
        ),
    ]
