# Generated by Django 4.2.7 on 2023-12-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0023_laporaneval_isdone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laporaneval',
            unique_together={('Nomor_Surat_Tugas', 'Nomor_Surat_Eval')},
        ),
    ]
