# Generated by Django 4.2.7 on 2023-12-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0024_alter_laporaneval_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laporaneval',
            unique_together={('Nomor_Surat_Eval',)},
        ),
    ]
