# Generated by Django 4.2.7 on 2023-12-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0025_alter_laporaneval_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanEval_Rekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rekomendasi', models.TextField(verbose_name='Hasil Rekomendasi')),
                ('Nomor_Surat_Eval', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat.laporaneval')),
            ],
            options={
                'unique_together': {('Nomor_Surat_Eval',)},
            },
        ),
    ]
