# Generated by Django 5.0.4 on 2024-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenda_surat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='desc',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
